"""
类型转换
int()：将字符串或数值转换为整数
float()：将字符串转换为浮点数
str()：将指定的对象转换为字符串形式
chr()：将整数转换为对应的字符编码
ord()：将字符转换成编码对应的整数
"""
print(int(12.3))
print(int("32"))
print(float("1.234"))
print(str(123))
print(chr(66))
print(ord("A"))